---
kind: pipeline
type: docker
name: plugins-test

steps:
- name: test
  image: golang:1.13.2
  commands:
    - mkdir -p $GOPATH/github.com/gravitational/teleport
    - git clone https://github.com/gravitational/teleport $GOPATH/github.com/gravitational/teleport
    - go get -v -t -d ./...
    - find . -type f -name "*.go" -exec sed -i 's_github.com/gravitational/teleport-plugins_github.com/webvictim/teleport-plugins_g' {} +
    - go test -v $(go list ./... | grep -v access/example)
