---
kind: pipeline
type: docker
name: plugins-test

steps:
- name: test
  image: golang:1.13.2
  commands:
    - find . -type f -name "*.go" -exec sed -i 's_github.com/gravitational/teleport-plugins_github.com/webvictim/teleport-plugins_g' {} +
    - go get -v -t -d ./...    
    - go test -v $(go list ./... | grep -v access/example)
