---
kind: pipeline
type: docker
name: plugins-test

clone:
  disable: true

steps: 
- name: test
  image: golang:1.13.2
  commands:
    - mkdir -p $GOPATH/src/github.com/gravitational/teleport-plugins
    - git clone https://github.com/webvictim/teleport-plugins.git $GOPATH/src/github.com/gravitational/teleport-plugins
    - cd $GOPATH/src/github.com/gravitational/teleport-plugins
    - git checkout $DRONE_COMMIT
    - go get -v -t -d ./...
    - make -C access/jirabot test
    - make -C access/slackbot test
    - make -C access/mattermost test
    - make -C access/pagerduty test
