# Golang CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.2
    working_directory: /go/src/github.com/gravitational/teleport-plugins
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      # check out code
      - run:
          name: Check out code
          command: |
            git clone https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git .
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
                git fetch origin pull/$CIRCLE_PR_NUMBER/head
            fi
            git reset --hard $CIRCLE_SHA1
      # restore module cache
      - restore_cache:
          keys:
            - go-cache-            
      # get dependencies
      - run:
          name: Get dependencies
          command: |
            go get -v -t -d ./...
            if [ -f Gopkg.toml ]; then
              curl -s https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure -v
            fi
      # run tests
      - run: 
          name: Run tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make -C access/jirabot test | tee -a ${TEST_RESULTS}/go-test.out
            make -C access/slackbot test  | tee -a ${TEST_RESULTS}/go-test.out
            make -C access/mattermost test  | tee -a ${TEST_RESULTS}/go-test.out
            make -C access/pagerduty test | tee -a ${TEST_RESULTS}/go-test.out
      # save module cache after successful run
      - save_cache:
          key: go-cache-
          paths:
            - "/go/pkg/mod"
      # store raw test output
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      # store test result output
      - store_test_results:
          path: /tmp/test-results
